version: 0.2

env:
  secrets-manager:
    LOGIN: sonarcreds:sonartoken
    HOST: sonarcreds:Host
    Organization: sonarcreds:Organization
    Project: sonarcreds:Project

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq unzip wget
      - apt install -y openjdk-17-jdk
      - java -version
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.10/binaries/apache-maven-3.9.10-bin.tar.gz
      - tar xzf apache-maven-3.9.10-bin.tar.gz
      - ln -s apache-maven-3.9.10 maven
      - export PATH=$PATH:$(pwd)/maven/bin
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-3.3.0.1492-linux/bin

  build:
    commands:
      - mvn test -Dtest=\!*PostgresIntegrationTests
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - echo "Waiting for SonarQube to process results"
      - sleep 10
      
      # Check quality gate status
      - echo "Checking quality gate status"
      - |
        TASK_ID=$(curl -s -u 14b0c1d6ede21ab6cd33fb7da8d553e77e62dbc2: https://sonarcloud.io/api/ce/activity?component=javafromcodepipeline | jq -r '.tasks[0].id')
        echo "Task ID: $TASK_ID"
        
        # Wait for analysis to complete
        TASK_STATUS="IN_PROGRESS"
        while [ "$TASK_STATUS" == "IN_PROGRESS" ]
        do
          TASK_STATUS=$(curl -s -u $SONAR_TOKEN: $SONAR_HOST_URL/api/ce/task?id=$TASK_ID | jq -r '.task.status')
          echo "Task status: $TASK_STATUS"
          if [ "$TASK_STATUS" == "IN_PROGRESS" ]; then
            echo "Analysis still in progress, waiting..."
            sleep 50
          fi
        done
        
        # Get quality gate status
        QUALITY_GATE_STATUS=$(curl -s -u $SONAR_TOKEN: $SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY | jq -r '.projectStatus.status')
        echo "Quality Gate Status: $QUALITY_GATE_STATUS"
        
        # Fail build if quality gate fails
        if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
          echo "Quality gate failed!"
          exit 1
        else
          echo "Quality gate passed!"
        fi

artifacts:
  files:
    - '**/*'
