version: 0.2

env:
  secrets-manager:
    $: sonarcreds:sonartoken
    HOST: sonarcreds:Host
    Organization: sonarcreds:Organization
    Project: sonarcreds:Project

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq unzip wget
      - apt install -y openjdk-17-jdk
      - java -version
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.10/binaries/apache-maven-3.9.10-bin.tar.gz
      - tar xzf apache-maven-3.9.10-bin.tar.gz
      - ln -s apache-maven-3.9.10 maven
      - export PATH=$PATH:$(pwd)/maven/bin
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-3.3.0.1492-linux/bin

  build:
    commands:
      - mvn test -Dtest=\!*PostgresIntegrationTests
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST/ -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      # Wait for SonarQube to process the results (adjust time as needed)
      - echo "Waiting for SonarQube to process results"
      - sleep 60  # Wait longer to ensure analysis is complete
      - |
          echo "Checking Quality Gate status..."
          QUALITY_GATE_STATUS=$(curl -s -u $LOGIN: $HOST/api/qualitygates/project_status?projectKey=$Project | jq -r '.projectStatus.status')
          echo "Quality Gate Status: $QUALITY_GATE_STATUS"
          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
            echo "Quality gate failed!!"
            exit 1
          else
            echo "Quality gate passed!!!"
          fi
artifacts:
  files:
    - '**/*'
