# Use the official NGINX base image
FROM public.ecr.aws/nginx/nginx:stable-perl

# Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

# Copy your custom static website or app files
COPY index.html /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

# Start NGINX (handled by base image's default CMD)
